"""empty message

Revision ID: e3549d4f40c4
Revises: 
Create Date: 2019-09-24 14:43:56.128248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3549d4f40c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('intro', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('org', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('scope', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'scope')
    op.drop_column('project', 'org')
    op.drop_column('project', 'intro')
    # ### end Alembic commands ###
